spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        - name: THORNTAIL_PROJECT_STAGE
          value: openshift
        - name: JAVA_APP_DIR
          value: /deployments
        - name: JAVA_OPTIONS
          value: -Ddb.service.database.url=jdbc:mysql://$(MYSQL_SIMPLESITE_SERVICE_HOST):$(MYSQL_SIMPLESITE_SERVICE_PORT)/simple_site 
                 -Ddb.service.database.username=simple_site_user 
                 -Ddb.service.database.password=Me6aKI6ENoCi